import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useSceneryStore = defineStore('scenery', () => {
  // 所有景点数据
  const allScenery = ref([
    // 安徽 (anhui)
    {
      id: 1,
      name: '池州',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%AE%89%E5%BE%BD/%E6%B1%A0%E5%B7%9E.jpeg',
      location: '安徽·池州',
      poem: '九华山上白云多，遥望江南水一波。',
      poet: '杜牧',
      description: '池州以九华山著称，是佛教名山之一。',
      tags: ['城市', '安徽'],
      province: 'anhui',
    },
    {
      id: 2,
      name: '合肥',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%AE%89%E5%BE%BD/%E5%90%88%E8%82%A5.jpeg',
      location: '安徽·合肥',
      poem: '淝水东流去，桑田几度秋。',
      poet: '李白',
      description: '合肥是安徽省会，历史悠久。',
      tags: ['城市', '安徽'],
      province: 'anhui',
    },
    {
      id: 3,
      name: '黄山',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%AE%89%E5%BE%BD/%E9%BB%84%E5%B1%B1.jpeg',
      location: '安徽·黄山',
      poem: '黄山四千仞，三十二莲峰。',
      poet: '李白',
      description: '黄山以奇松、怪石、云海、温泉"四绝"闻名于世。',
      tags: ['山岳', '自然景观', '世界遗产', '安徽'],
      province: 'anhui',
    },
    {
      id: 4,
      name: '芜湖',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%AE%89%E5%BE%BD/%E8%8A%9C%E6%B9%96.jpeg',
      location: '安徽·芜湖',
      poem: '芜湖烟雨湿江城，帆影斜阳画不成。',
      poet: '近现代',
      description: '芜湖为长江重要港口城市。',
      tags: ['城市', '安徽'],
      province: 'anhui',
    },
    {
      id: 5,
      name: '黟县',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%AE%89%E5%BE%BD/%E6%AD%99%E5%8E%BF.jpeg',
      location: '安徽·黟县',
      poem: '黟山秀色画难成，流水高低自有声。',
      poet: '明·唐寅',
      description: '黟县以宏村、西递等古村落著称。',
      tags: ['古镇', '安徽'],
      province: 'anhui',
    },
    {
      id: 6,
      name: '歙县',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%AE%89%E5%BE%BD/%E6%AD%99%E5%8E%BF.jpeg',
      location: '安徽·歙县',
      poem: '歙溪春水绿，见底石磷磷。',
      poet: '杜牧',
      description: '歙县是徽州文化的发源地。',
      tags: ['古镇', '安徽'],
      province: 'anhui',
    },
    // 北京 (beijing)
    {
      id: 7,
      name: '长城',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%8C%97%E4%BA%AC/%E5%85%AB%E8%BE%BE%E5%B2%AD%E9%95%BF%E5%9F%8E.jpeg',
      location: '北京',
      poem: '但使龙城飞将在，不教胡马度阴山。',
      poet: '王昌龄',
      description: '长城是世界七大奇迹之一。',
      tags: ['古迹', '世界遗产', '北京'],
      province: 'beijing',
    },
    {
      id: 8,
      name: '故宫',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%8C%97%E4%BA%AC/%E6%95%85%E5%AE%AB.jpeg',
      location: '北京',
      poem: '紫禁城中秋月明，菊花香露湿流萤。',
      poet: '李商隐',
      description: '故宫是中国明清两代的皇家宫殿。',
      tags: ['古建筑', '历史遗迹', '世界遗产', '北京'],
      province: 'beijing',
    },
    {
      id: 9,
      name: '南锣鼓巷',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%8C%97%E4%BA%AC/%E5%8D%97%E9%94%A3%E9%BC%93%E6%B8%AF.png',
      location: '北京',
      poem: '胡同深处旧时光，青砖灰瓦忆京腔。',
      poet: '现代',
      description: '南锣鼓巷是北京最古老的街区之一。',
      tags: ['胡同', '商业街', '北京'],
      province: 'beijing',
    },
    {
      id: 10,
      name: '鸟巢',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%8C%97%E4%BA%AC/%E9%B8%9F%E5%B7%A2.jpeg',
      location: '北京',
      poem: '燕雀安知鸿鹄志，巢居高处望天涯。',
      poet: '借用古意',
      description: '鸟巢是2008年北京奥运会的主体育场。',
      tags: ['现代建筑', '体育场馆', '北京'],
      province: 'beijing',
    },
    {
      id: 11,
      name: '天安门',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%8C%97%E4%BA%AC/%E5%A4%A9%E5%AE%89%E9%97%A8%E5%B9%BF%E5%9C%BA.jpeg',
      location: '北京',
      poem: '万国衣冠拜冕旒，天安门上看神州。',
      poet: '现代',
      description: '天安门是中华人民共和国的象征。',
      tags: ['地标', '广场', '北京'],
      province: 'beijing',
    },
    {
      id: 12,
      name: '天坛',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%8C%97%E4%BA%AC/%E5%A4%A9%E5%9D%9B.jpeg',
      location: '北京',
      poem: '琼台玉宇接天坛，祈谷声中瑞气还。',
      poet: '现代',
      description: '天坛是明清两代皇帝祭祀皇天的场所。',
      tags: ['古建筑', '祭祀', '世界遗产', '北京'],
      province: 'beijing',
    },
    {
      id: 13,
      name: '颐和园',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%8C%97%E4%BA%AC/%E9%A2%90%E5%92%8C%E5%9B%AD.jpeg',
      location: '北京',
      poem: '万树垂杨绕玉堤，昆明湖上画船稀。',
      poet: '清·洪亮吉',
      description: '颐和园是中国清朝时期的皇家园林。',
      tags: ['皇家园林', '世界遗产', '北京'],
      province: 'beijing',
    },
    {
      id: 14,
      name: '圆明园',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%8C%97%E4%BA%AC/%E5%9C%86%E6%98%8E%E5%9B%AD.jpeg',
      location: '北京',
      poem: '劫后园林空断碧，残荷犹带旧时香。',
      poet: '现代',
      description: '圆明园曾是清代著名的皇家园林。',
      tags: ['遗址公园', '皇家园林', '北京'],
      province: 'beijing',
    },
    // 江苏 (jiangsu)
    {
      id: 15,
      name: '南京',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B1%9F%E8%8B%8F/%E5%8D%97%E4%BA%AC.jpeg',
      location: '江苏·南京',
      poem: '烟笼寒水月笼沙，夜泊秦淮近酒家。',
      poet: '杜牧',
      description: '南京是六朝古都，历史文化名城。',
      tags: ['古都', '城市', '江苏'],
      province: 'jiangsu',
    },
    {
      id: 16,
      name: '苏州',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B1%9F%E8%8B%8F/%E8%8B%8F%E5%B7%9E.jpeg',
      location: '江苏·苏州',
      poem: '姑苏城外寒山寺，夜半钟声到客船。',
      poet: '张继',
      description: '苏州以园林和水乡著称。',
      tags: ['园林', '江南水乡', '江苏'],
      province: 'jiangsu',
    },
    {
      id: 17,
      name: '无锡',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B1%9F%E8%8B%8F/%E6%97%A0%E9%94%A1.jpeg',
      location: '江苏·无锡',
      poem: '太湖佳绝处，毕竟在鼋头。',
      poet: '郭沫若',
      description: '无锡有太湖美景和灵山大佛。',
      tags: ['城市', '太湖', '江苏'],
      province: 'jiangsu',
    },
    {
      id: 18,
      name: '扬州',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B1%9F%E8%8B%8F/%E6%89%AC%E5%B7%9E.jpeg',
      location: '江苏·扬州',
      poem: '故人西辞黄鹤楼，烟花三月下扬州。',
      poet: '李白',
      description: '扬州以瘦西湖和淮扬菜闻名。',
      tags: ['历史名城', '园林', '江苏'],
      province: 'jiangsu',
    },
    {
      id: 19,
      name: '镇江',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B1%9F%E8%8B%8F/%E9%95%87%E6%B1%9F.jpeg',
      location: '江苏·镇江',
      poem: '京口瓜洲一水间，钟山只隔数重山。',
      poet: '王安石',
      description: '镇江以金山寺等著名景点和镇江香醋闻名。',
      tags: ['城市', '江苏'],
      province: 'jiangsu',
    },
    {
      id: 20,
      name: '周庄',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B1%9F%E8%8B%8F/%E5%91%A8%E5%BA%84.jpeg',
      location: '江苏·苏州',
      poem: '小桥流水人家，古镇悠悠岁月。',
      poet: '现代',
      description: '周庄是中国第一水乡。',
      tags: ['古镇', '水乡', '江苏'],
      province: 'jiangsu',
    },
    // 陕西 (shanxi)
    {
      id: 21,
      name: '宝鸡',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E9%99%95%E8%A5%BF/%E5%AE%9D%E9%B8%A1.jpeg',
      location: '陕西·宝鸡',
      poem: '宝鸡山色翠如屏，渭水东流绕古城。',
      poet: '现代',
      description: '宝鸡是炎帝故里，青铜器之乡。',
      tags: ['城市', '陕西'],
      province: 'shanxi',
    },
    {
      id: 22,
      name: '汉中',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E9%99%95%E8%A5%BF/%E6%B1%89%E4%B8%AD.jpeg',
      location: '陕西·汉中',
      poem: '汉水波声远，巴山夜雨多。',
      poet: '李白',
      description: '汉中是汉文化的重要发源地。',
      tags: ['城市', '陕西'],
      province: 'shanxi',
    },
    {
      id: 23,
      name: '华山',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E9%99%95%E8%A5%BF/%E5%8D%8E%E5%B1%B1.jpeg',
      location: '陕西·渭南',
      poem: '只有天在上，更无山与齐。',
      poet: '寇准',
      description: '华山以险峻著称，是五岳中的西岳。',
      tags: ['山岳', '五岳', '陕西'],
      province: 'shanxi',
    },
    {
      id: 24,
      name: '渭南',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E9%99%95%E8%A5%BF/%E6%B8%AD%E5%8D%97.jpeg',
      location: '陕西·渭南',
      poem: '渭水自萦秦塞曲，黄山旧绕汉宫斜。',
      poet: '杜甫',
      description: '渭南地处关中平原东部。',
      tags: ['城市', '陕西'],
      province: 'shanxi',
    },
    {
      id: 25,
      name: '西安',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E9%99%95%E8%A5%BF/%E8%A5%BF%E5%AE%89.jpeg',
      location: '陕西·西安',
      poem: '长安回望绣成堆，山顶千门次第开。',
      poet: '杜牧',
      description: '西安是世界四大古都之一。',
      tags: ['古都', '历史遗迹', '陕西'],
      province: 'shanxi',
    },
    {
      id: 26,
      name: '延安',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E9%99%95%E8%A5%BF/%E5%BB%B6%E5%AE%89.jpeg',
      location: '陕西·延安',
      poem: '几回回梦里回延安，双手搂定宝塔山。',
      poet: '贺敬之',
      description: '延安是中国革命圣地。',
      tags: ['革命圣地', '红色旅游', '陕西'],
      province: 'shanxi',
    },
    // 四川 (sichuan)
    {
      id: 27,
      name: '阿坝',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%9B%9B%E5%B7%9D/%E9%98%BF%E5%9D%9D.jpeg',
      location: '四川·阿坝',
      poem: '雪山草地阿坝美，藏羌风情入画来。',
      poet: '现代',
      description: '欢迎来到阿坝藏族羌族自治州。这里有壮丽的自然风光和独特的民族文化。',
      tags: ['高原风光', '民族地区', '四川'],
      province: 'sichuan',
    },
    {
      id: 28,
      name: '川西',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%9B%9B%E5%B7%9D/%E5%B7%9D%E8%A5%BF.jpeg',
      location: '四川·川西',
      poem: '蜀道难，难于上青天。',
      poet: '李白',
      description: '川西高原风光旖旎，是摄影和自驾爱好者的天堂。',
      tags: ['高原风光', '自然景观', '四川'],
      province: 'sichuan',
    },
    {
      id: 29,
      name: '稻城',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%9B%9B%E5%B7%9D/%E7%A8%BB%E5%9F%8E.jpeg',
      location: '四川·甘孜',
      poem: '天地有大美而不言，稻城亚丁似仙源。',
      poet: '现代',
      description: '稻城亚丁被誉为“蓝色星球上的最后一片净土”，以其雪山、草甸、湖泊闻名。',
      tags: ['高原风光', '自然保护区', '四川'],
      province: 'sichuan',
    },
    {
      id: 30,
      name: '峨眉山',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%9B%9B%E5%B7%9D/%E5%B3%A8%E7%9C%89%E5%B1%B1%E5%B8%82.jpeg',
      location: '四川·乐山',
      poem: '蜀国多仙山，峨眉邈难匹。',
      poet: '李白',
      description: '峨眉山是中国四大佛教名山之一，以秀丽的自然风光和悠久的佛教文化著称。',
      tags: ['佛教名山', '世界遗产', '四川'],
      province: 'sichuan',
    },
    {
      id: 31,
      name: '九寨沟',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E5%9B%9B%E5%B7%9D/%E4%B9%9D%E5%AF%A8%E6%B2%9F.png',
      location: '四川·阿坝',
      poem: '翠湖碧波映山色，彩林红叶舞秋风。',
      poet: '现代',
      description: '九寨沟以其碧蓝的湖水、叠瀑、彩林和雪山闻名于世，被誉为"人间仙境"。',
      tags: ['自然景观', '湖泊', '世界遗产', '四川'],
      province: 'sichuan',
    },
    // 浙江 (zhejiang)
    {
      id: 32,
      name: '东栅',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B5%99%E6%B1%9F/%E4%B8%9C%E7%8F%8A.jpeg',
      location: '浙江·嘉兴',
      poem: '乌镇水乡多古意，东栅烟雨画中游。',
      poet: '现代',
      description: '乌镇东栅保留了原汁原味的江南水乡风貌和民俗文化。',
      tags: ['古镇', '水乡', '浙江'],
      province: 'zhejiang',
    },
    {
      id: 33,
      name: '杭州',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B5%99%E6%B1%9F/%E6%9D%AD%E5%B7%9E.jpeg',
      location: '浙江·杭州',
      poem: '欲把西湖比西子，淡妆浓抹总相宜。',
      poet: '苏轼',
      description: '杭州以西湖闻名，是历史文化名城和重要的电子商务中心。',
      tags: ['城市', '西湖', '浙江'],
      province: 'zhejiang',
    },
    {
      id: 34,
      name: '宁波',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B5%99%E6%B1%9F/%E5%AE%81%E6%B3%A2.jpeg',
      location: '浙江·宁波',
      poem: '三江汇海通舟楫，万里潮声到甬城。',
      poet: '现代',
      description: '宁波是历史悠久的港口城市，文化底蕴深厚。',
      tags: ['港口城市', '浙江'],
      province: 'zhejiang',
    },
    {
      id: 35,
      name: '绍兴',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B5%99%E6%B1%9F/%E7%BB%8D%E5%85%B4.jpeg',
      location: '浙江·绍兴',
      poem: '鉴湖水似碧，越女采莲归。',
      poet: '唐·李白',
      description: '绍兴是著名的水乡、桥乡、酒乡、书法之乡、名士之乡。',
      tags: ['水乡', '历史名城', '浙江'],
      province: 'zhejiang',
    },
    {
      id: 36,
      name: '乌镇',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B5%99%E6%B1%9F/%E4%B9%8C%E9%95%87.png',
      location: '浙江·嘉兴',
      poem: '乌蓬小艇穿街过，水巷人家尽枕河。',
      poet: '现代',
      description: '乌镇是典型的江南水乡古镇，是世界互联网大会永久举办地。',
      tags: ['古镇', '水乡', '浙江'],
      province: 'zhejiang',
    },
    {
      id: 37,
      name: '西塘',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B5%99%E6%B1%9F/%E8%A5%BF%E5%A1%98.jpeg',
      location: '浙江·嘉兴',
      poem: '烟雨长廊西塘美，水巷人家画里行。',
      poet: '现代',
      description: '西塘古镇以桥多、弄多、廊棚多而闻名，生活气息浓郁。',
      tags: ['古镇', '水乡', '浙江'],
      province: 'zhejiang',
    },
    {
      id: 38,
      name: '舟山',
      image: 'https://ancient-poem-img.oss-cn-beijing.aliyuncs.com/tourist/%E6%B5%99%E6%B1%9F/%E8%88%9F%E5%B1%B1.jpeg',
      location: '浙江·舟山',
      poem: '海上生明月，天涯共此时。',
      poet: '张九龄',
      description: '舟山是中国唯一的群岛地级市，以渔业和佛教圣地普陀山闻名。',
      tags: ['群岛', '海滨城市', '浙江'],
      province: 'zhejiang',
    },
  ])

  // 按省份分类的景点
  const sceneryByProvince = computed(() => {
    const map = {}
    allScenery.value.forEach(item => {
      if (!map[item.province]) map[item.province] = []
      map[item.province].push(item)
    })
    return map
  })

  // 获取全部景点
  const getAllScenery = computed(() => allScenery.value)

  // 获取指定省份的景点
  const getSceneryByProvince = (province) => {
    if (province === 'all') return allScenery.value
    return sceneryByProvince.value[province] || []
  }

  return {
    allScenery,
    sceneryByProvince,
    getAllScenery,
    getSceneryByProvince,
  }
})