/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cartoon: typeof import('./components/cartoon/cartoon.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Header: typeof import('./components/header/header.vue')['default']
    Modal: typeof import('./components/nodeCard/modal.vue')['default']
    Newcard: typeof import('./components/nodeCard/newcard.vue')['default']
    NodeCard: typeof import('./components/nodeCard/index.vue')['default']
    Pagenation: typeof import('./components/pagenation/pagenation.vue')['default']
    Poetryitem: typeof import('./components/poetryitem/poetryitem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/search/search.vue')['default']
    Searchsen: typeof import('./components/search/searchsen.vue')['default']
    Searchwriter: typeof import('./components/search/searchwriter.vue')['default']
    Textcartoon: typeof import('./components/textcartoon/textcartoon.vue')['default']
    Writeitem: typeof import('./components/writeritem/writeitem.vue')['default']
    Writercontent: typeof import('./components/wriercontent/writercontent.vue')['default']
  }
}
